# Nome da Pipeline
name: TDW_Tomas_Sousa#1

# Quando a pipeline vai correr. Sempre que houver commit para qualquer branch (push) ou sempre que houver um pull request para qualquer branch
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

# Definição dos jobs que vão correr em paralelo
jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instalar dependências
      - name: Install dependencies
        run: npm install
        working-directory: ./aula_02-10

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install-dependencies  # Isto depende de install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Correr todos os testes automáticos
      - name: Run tests
        run: npm run test
        working-directory: ./aula_02-10

  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    needs: run-tests  # Isto depende da passagem dos testes
    if: success()  # Só vai se bem sucedido
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Fazer build do Projeto
      - name: Build project
        run: npm run build
        working-directory: ./aula_02-10
